Bots grecia
kmlv/TaxGovEffectCorruption pull request #15
Opened 2022-02-05 17:17 UTC by Sweetdreamstome

2022-02-10 02:04 UTC, Sweetdreamstome commented
@mgutierrezc ya no hay más conflictos para hacer el merge con el master!

2022-02-10 05:30 UTC, mgutierrezc requested changes
@Sweetdreamstome 
- Actualizar `requirements.txt` para los paquetes que están usando y no están allí. E.g: `simplejson`
- Activar los bots en todos los juegos
- asegurarse de que no se commiteen los archivos de la carpeta `__temp_static_root` (añadir al `.gitignore` de ser necesario y seguir mismos pasos con los que solucionarion `db.sqlite3`

2022-02-10 15:02 UTC, Sweetdreamstome commented
@mgutierrezc ya agregué al .gitignore db.sqlite, realicé el respectivo merge con master y actualicé requirements.txt.

2022-02-10 17:59 UTC, mgutierrezc commented
Genial! @Sweetdreamstome Activaste los bots en todos los juegos?

2022-02-10 18:07 UTC, Sweetdreamstome commented
@mgutierrezc siii, corrí las 4 apps con el último commit que realicé y corren a la perfección.

2022-02-11 12:51 UTC, Sweetdreamstome commented
@mgutierrezc  no te olvides, hacerle pull a este branch por fis!

2022-02-12 01:19 UTC, mgutierrezc commented
@Sweetdreamstome carpetas de archivos temporales no deben ser pusheadas al repo
![image](https://user-images.githubusercontent.com/43623521/153690516-7188d701-940f-4528-8496-167048d74234.png)

2022-02-12 01:31 UTC, mgutierrezc commented
Solucionado

2022-02-12 01:31 UTC, merged