Paragraph same max payoff
kmlv/TaxGovEffectCorruption pull request #24
Opened 2022-02-23 04:36 UTC by Sergio2405

Instructions paragraph specifying that all apps have approx the same max payoff.

2022-02-23 18:17 UTC, Sergio2405 commented
@mgutierrezc de paso he hecho la tarea de "code payment info app". La pagina donde te muestra los pagos se ve asi: 
![image](https://user-images.githubusercontent.com/67673799/155382071-62305225-3114-4e48-9d49-7e97c5c24739.png)

2022-02-24 03:09 UTC, mgutierrezc commented
@Sergio2405 está lista para ser revisada?

2022-02-24 04:30 UTC, Sergio2405 commented
> @Sergio2405 está lista para ser revisada?

@mgutierrezc Si

2022-02-25 02:00 UTC, mgutierrezc commented
@Sergio2405 has merge con el master

2022-02-25 02:01 UTC, mgutierrezc commented
@Sergio2405 es decir, primero mergea master con este branch y luego reviso el PR. @Sweetdreamstome ha hecho un PR hace poco y el master tiene nuevos commits

2022-02-25 13:12 UTC, Sergio2405 commented
> @Sergio2405 es decir, primero mergea master con este branch y luego reviso el PR. @Sweetdreamstome ha hecho un PR hace poco y el master tiene nuevos commits

@mgutierrezc cuando yo cree este branch lo hice en base al master luego de que grecia haya hecho su PR

2022-02-25 20:59 UTC, mgutierrezc requested changes

2022-02-25 20:59 UTC, mgutierrezc commented on coin_tossing/pages.py
>  class RoundResults(Page):
Queda un poco confuso que aqui se llame a "pay_random_app" cuando ya no se decide nada en coin tossing. Borremos y debuggeemos este codigo @Sergio2405

2022-02-25 21:23 UTC, Sergio2405 commented on coin_tossing/pages.py
>  class RoundResults(Page):
@mgutierrezc Si marco claro eso estaba como comentario no lo borré porque pensé que tal vez podía servir para algo

2022-02-25 21:45 UTC, Sergio2405 commented
@mgutierrezc Marco ya hice el commit con eso de "pay_random_app" borrado asi y ya lo debugee

2022-02-25 22:36 UTC, mgutierrezc approved these changes

2022-02-25 22:36 UTC, merged